mariadb:
  image: mariadb:latest
  port:
    - 3306:3306
  volumes:
    - ./db:/var/lib/mysql
  restart: unless-stopped
  environment:
    - MARIADB_ROOT_PASSWORD=password
    - MARIADB_USER=user
    - MARIADB_PASSWORD=password
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.labels.name == manager
    restart_policy:
      condition: on-failure