nginx:
  image: nginx:latest
  port:
    - 8080:80
  volumes:
    - ./www:/var/www
    - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
  links:
    - php
  restart: unless-stopped
  environment:
    - NGINX_PORT=80
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.labels.name == manager
    restart_policy:
      condition: on-failure